apiVersion: apps/v1
kind: Deployment
metadata:
  name: prophesizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prophesizer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prophesizer
    spec:
      containers:
      - image: corvimae/prophesizer:1.0.1
        imagePullPolicy: Always
        name: prophesizer
        resources: {}
        env:
        - name: PSQL_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: prophesizer-secrets
              key: psqlConnectionString
        - name: AWS_KEY
          valueFrom:
            secretKeyRef:
              name: prophesizer-secrets
              key: awsKey
        - name: AWS_SECRET
          valueFrom:
            secretKeyRef:
              name: prophesizer-secrets
              key: awsSecret
      restartPolicy: Always
status: {}
